restructured and added .gitignore file
DilshodMura/git-tutorial pull request #5
Opened 2021-01-04 17:53 UTC by DilshodMura

2021-01-04 18:16 UTC, rustam-umarov requested changes

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +            for (int i = 0;; i++)
`for` обычно используется, когда ты знаешь когда цикл должен остановиться. В твоем случае ты этого не знаешь и выходишь из цикла только когда твое условие попадает в `if statement`, поэтому было бу лучше использовать `while`.

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +
nit: ненужный пробел

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +
два ненужных пробела

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +
еще пробел

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +    }
скобка не на своем уровне

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +                if (input1 == c)
постарайся не называть переменную `input1`, дай ей какое-то свойственное название

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +        static void Main(string[] args)
напиши метод фибоначи в своей отдельном методе и вызывай его из данного `Main` метода

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +            Console.WriteLine("please enter your nubmer...");
в данном случае ты можешь не считывать инпут, а лучше просто передавай его значение в метод

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +            int a = 0;
точно также поменяй названия `a, b, c` на что-то, что будет тебе понятно, если тебе придется посмотреть на этот код через год

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving/Program.cs
> +        //static void Fibonacci(int a)
коментарии такого рода не приветствуются

2021-01-04 18:16 UTC, rustam-umarov commented on ProblemSolving.Test/ProblemSolvingTest.cs
> +        public void TestMethod1()
после того как ты исправишь вещи, про которые я написал, можно приступить к написанию теста, чтобы проверить правильно ли ты решил задачу

2021-01-07 13:43 UTC, DilshodMura commented on ProblemSolving/Program.cs
> +            for (int i = 0;; i++)
If statement was replaced by while loop
`  for (int i = 0; ; i++)
            {
                result = input + input2;
                input = result - input;
                input2 = result;

                //inserted while loop instead of if else statement
                while ((input1 == result) && (input1 < result))
                {
                    Console.WriteLine("Fibonacci");
                    break;
                }

            }`

2021-01-07 16:59 UTC, DilshodMura commented on ProblemSolving/Program.cs
> +            for (int i = 0;; i++)
for loop has been replaced on while loop. 
` while (true) 
            {
                result = input + input2;
                input = result - input;
                input2 = result;

                //inserted while loop instead of if else statement
                if (input1 == result)
                {
                    Console.WriteLine("Fibonacci");
                    break;
                }
               else if (input1 < result)
                {
                    Console.WriteLine("Not Fibonacci");
                    break;
                }
                
            }`

2021-01-07 17:03 UTC, DilshodMura commented on ProblemSolving/Program.cs
> +
extra space was taken off

2021-01-07 17:03 UTC, DilshodMura commented on ProblemSolving/Program.cs
> +        static void Main(string[] args)
Fibonacci method 
`static void Fibonacci()
        {
            var input1 = int.Parse(Console.ReadLine());
            int input = 0;
            int input2 = 1;
            int result;

            while (true) 
            {
                result = input + input2;
                input = result - input;
                input2 = result;

                //inserted while loop instead of if else statement
                if (input1 == result)
                {
                    Console.WriteLine("Fibonacci");
                    break;
                }
               else if (input1 < result)
                {
                    Console.WriteLine("Not Fibonacci");
                    break;
                }
                
            }

        }`

2021-01-07 17:05 UTC, DilshodMura commented on ProblemSolving/Program.cs
> +            int a = 0;
a b c was changed to input,input2, and result

2021-01-07 17:06 UTC, DilshodMura commented on ProblemSolving/Program.cs
> +        //static void Fibonacci(int a)
the comment was changed to new method Fibonacci

2021-01-07 23:05 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +            var easyTasks = new EasyTasks(); //creating an instance of EasyTasks
Looks great! one minor thing to point out - since we're instantiating `EasyTasks` class in multiple places (in IsFibonacciHappyPath_13 and in IsFibonacciFailPath_14), we will need to instantiate it once on class level, so that every method could access it without re-instantiating all the time.

2021-01-07 23:05 UTC, rustam-umarov commented on README.md
> +- Make sure to write at least 3 happy path unit tests and 3 unhappy path unit tests
Please, add 2 more happy path and 2 more fail path unit tests to make sure `IsFibonacci()` method is functioning properly (larger input and negative numbers are highly encouraged).

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +
пробел)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +
пробел)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +
пробел)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +
пробел)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +        //1. Hppy path
не оставляй такие коменты в коде

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +
пробел)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +
пробел)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +    }
скобка)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +
пробел)

2021-01-11 15:35 UTC, rustam-umarov commented on ProblemSolving.Core/EasyTasks.cs
> +            //here goes the solution
можно убрать комент и написать чуть проще:
```
public int SumOfTwo(int firstInput, int secondInput)
{
     return firstInput + secondInput;
}
```

2021-01-11 15:46 UTC, rustam-umarov commented on ProblemSolving.Tests/EasyTasksTests.cs
> +            var easyTasks = new EasyTasks(); //creating an instance of EasyTasks
@DilshodMura посмотрел эти коменты?

2021-01-28 17:40 UTC, rustam-umarov approved these changes

2021-01-28 17:46 UTC, merged